version: '3.8'

services:
  whitefox5:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whitefox5_app
    ports:
      - "8080:80"
    restart: always
    environment:
      - NODE_ENV=production
